
#Create Unlimited Config
[CreateUnlimited]

	#Train Settings
	[CreateUnlimited.Trains]
		#Whether or not to enable the placement checks for train tracks.
		#Allowed Values: ON, SURVIVAL_ONLY, OFF
		placementChecksEnabled = "ON"
		#Whether or not to allow trains to drive on "very illegal" tracks. Slightly buggy.
		veryIllegalDriving = false
		#Maximum distance a train can be relocated using the wrench.
		#Range: > 0
		maxTrainRelocatingDistance = 24
		#Maximum stress from couplings before train derails. Set to -1 to disable.
		#Range: -1.0 ~ 1.7976931348623157E308
		maxAllowedStress = 4.0

	#Glue Settings
	[CreateUnlimited.SuperGlue]
		#Maximum distance between two blocks for them to be considered for glue connections.
		#Range: > 0
		maxGlueConnectionRange = 24
		#Require blocks to be connected for glue connections.
		blocksMustBeConnectedForConnection = true

	#Extendo Grip Settings
	[CreateUnlimited.ExtendoGrip]
		#How much to extend your reach when holding an Extendo-Grip. Adds to your base reach.
		#Range: > 0
		singleExtendoGripRange = 3
		#How much to extend your reach when holding two Extendo-Grips. Adds to your base reach.
		#Range: > 0
		doubleExtendoGripRange = 5

